### ISSUE TITLE
Feature: User can search a keyword

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

<!-- write your feature below this line, i.e. "User can..." -->

User can search the Rick and Morty public API using keyword(s).

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

<!-- write your plan below this line -->

User can type into the search bar using the character name, or a keyword.  Once submitted, a list of characters  is loaded from the Rick and Morty API and displayed on the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103544497/202054920-4b5df863-2961-4540-903e-a69a697daa34.png)

![image](https://user-images.githubusercontent.com/103544497/202054972-b98fdbbf-f5ff-44c8-9316-315926279a47.png)




## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML skeleton.
- [x] Create header element.
- [x] Create proper divs/containers for page content.
- [x] Create html form element, to hold input and search(submit)                                                                                                                                                                                                                                                                            button.
- [x] Provide proper CSS styling to match wireframe.
- [x] Listen for 'submit' events on the form element.
- [x] Query select for button/submit element.
- [x] Write handle submit function with parameter that will receive character name from input. 
- [x] Within character name function create new instance of XMLHttpRequest and set to xhr variable.
- [x] Write xhr.open method called with two arguments, 'GET' and string for Rick and Morty API with concatenation of characterName parameter.
- [x] Assign string 'json' to xhr.responseType.
- [x] Check to make sure proper data is being received by console logging the xhr object.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
