### ISSUE TITLE
Feature: User can can view the list of results from search.

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of characters.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will type a name of a character or keyword/trait of a character, then hit search.  The page will then switch to a list of one or more versions of that character.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103544497/202056567-d2784bce-df6e-4841-9c5d-6b379b4b534c.png)
![image](https://user-images.githubusercontent.com/103544497/202056597-0a2cad1f-0f72-499b-9aa2-561a131ca676.png)
![image](https://user-images.githubusercontent.com/103544497/202056633-ddc68e51-44ec-461c-83e7-d3d6b2a80be1.png)
![image](https://user-images.githubusercontent.com/103544497/202056682-170c47df-dc95-470b-9083-5071191bf94e.png)
![image](https://user-images.githubusercontent.com/103544497/202328458-13996ab8-7e40-4f98-a924-41e357024f11.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling div element to the div with class row within the main element.
- [x] Add necessary divs to sibling div element for proper column and row setup.
- [x] Add an empty unordered list to sibling div element.  
- [x] Ensure that when clicking the search button, the search 'page' is hidden, and the results. 'page' is shown.
- [x] Define a function that takes the xhr.response object and returns a DOM tree with a list element, an image element, and two paragraph elements.
- [x] Append the DOM tree created to the empty unordered list element in the HTML.
- [x] Ensure CSS and styling for both mobile and desktop are correct.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
