### ISSUE TITLE
Feature: User can can view the details of a single character.

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of a single character.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks on any picture from the results list, the view will swap to the details page, which will then have a single image with more information about that specific character.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103544497/202590047-c18a6f18-3d49-4c5a-b6be-6b9f9da4c62c.png)
![image](https://user-images.githubusercontent.com/103544497/202589868-5c3556ba-94c5-432e-a577-cbd6affb1053.png)
![image](https://user-images.githubusercontent.com/103544497/202589895-3fa92a9e-78f0-446c-adf1-46bd1670c943.png)
![image](https://user-images.githubusercontent.com/103544497/202589923-e38b0a71-19a1-4e07-8744-44d38ebbf752.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling div element with class "container-details" to div element with class "results-container".
- [x] Add proper div element row and column structure for details div.
- [x]  Assign an empty object to variable characterData within getCharacterLi function.
- [x] Assign all necessary values to characterData object, using values of xhr object passed through getCharacterLi function.
- [x] Push characterData object to entries value (empty array) of the data model object.
- [x] Set attribute of DOM created li element to data-character-id = value obtained from xhr object (character.id).
- [x] Add event listener to unordered list element.
- [x] Create callback function to handle click events in the unordered list.
- [x] Assign query Selectors for variables name, status, species, gender, origin, last known location and image.
- [x] Assign event.target.closet('[data-character-id]') to variable liCharacter selector.
- [x] Create for loop that loops over data.entries.length.
- [x] If the attribute number of data-character-id is equal to character ID from data.entries then assign specified values to query selected variables in the html.
- [x] Add transition effects to CSS styles.
- [x] Ensure all functionality and CSS is proper for both mobile and desktop views.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
