### ISSUE TITLE
Feature: User can can add a character, with associated info, to their online collection.

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a character, and associated info, to their collection/database.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user is viewing the details page, they can click on the 'add to database' button to add whichever character they are currently viewing to their personal database page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103544497/202945202-ca6d5fd4-1407-4945-82c3-24d843411e9e.png)
![image](https://user-images.githubusercontent.com/103544497/202945238-a62c8df2-451c-4a06-bfa0-96dfc1713194.png)
![image](https://user-images.githubusercontent.com/103544497/202945288-4ac96476-9d41-4992-9821-92dbc4babaec.png)
![image](https://user-images.githubusercontent.com/103544497/202945305-bd05968f-a5cb-47e5-a8c5-d95ae5560302.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an anchor element as a sibling to unordered list within div with class="column-half details-text-container".
- [x] Style anchor element to appear as a clickable button.
- [x] Ensure CSS styling matches figma, and appears proper for both mobile and desktop views. 
- [x] Add sibling div with class="container-database-page hidden" and data-view="data-database-page" to div with class="container-results".
- [x] Add proper row and column divs.
- [x] Add empty child div with class="row database-char-img".
- [x] Add event listener that listens for 'click' events on anchor element.
- [x] Define callback function for 'click' event.- [ ] 
- [x] Within callback function, add view swap functionality to show 'database page' when anchor element is clicked.
- [x] Define a function for creating a new DOM tree for 'database page'.
- [x] Within click event callback function, determine which image and details info is being viewed on 'details page', and store in data model.
- [x] Call the function which defines the new DOM tree and pass in the data stored in the data model as its argument.
- [x] Append the return of the DOM tree function to the empty unordered list in the HTML.
- [x] Check all functionality and CSS stylings.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
