### ISSUE TITLE
Feature: User can can view their character collection.

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view character details in personal Database

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After a character has been added to the personal databases view from the details page, a user will be able to click on that specific character and the character card will flip, showing the details information on the back of the card.  User will then be able to click again to flip card and reveal the image.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103544497/203626199-2217d28f-7dce-47a4-8401-885fdea09871.png)
![image](https://user-images.githubusercontent.com/103544497/203626337-592f8f85-f2ef-4fc5-a889-d541866a73ee.png)
![image](https://user-images.githubusercontent.com/103544497/203629691-024db65e-1cf2-4fd8-b5dd-8b5b0dd2bf35.png)
![image](https://user-images.githubusercontent.com/103544497/203629827-50565ef9-35b1-449c-a9ab-1f182954eedf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add 'click' event listener to listen for click on images (cards) in personal database view. 
- [x] Add necessary CSS styling for card flip functionality.
- [x] Ensure CSS for information displayed on back of card is proper.
- [x] Ensure CSS styling is correct for both mobile and desktop views..
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
